/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package git.semver.plugin.gradle

import git.semver.plugin.scm.Commit
import git.semver.plugin.semver.SemverSettings
import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class ChangeLogFormatterTest {
    @Test fun format_log_empty() {
        val settings = SemverSettings()

        val actual = ChangeLogFormatter(settings, settings.changeLogTexts).formatLog(listOf())

        assertThat(actual).startsWith("## What's Changed")
    }

    @Test fun format_log_with_breaking_changes() {
        val settings = SemverSettings()
        val changeLog = createChangeLog()

        val actual = ChangeLogFormatter(settings, settings.changeLogTexts).formatLog(changeLog)

        assertThat(actual)
            .startsWith("## What's Changed")
            .containsOnlyOnce("Bugfix 1")
            .contains("### Breaking Changes")
            .contains("  - fix(#5)!: A breaking change")
            .contains("    more text")
            .contains("### Bug Fixes")
            .contains("- build(deps): A build change")
            .contains("- A CI change")
            .contains("### Tests")
            .contains("- Added some tests")
            .contains("### New Features")
            .contains("- #2: A feature")
            .contains("- xyz: Some other change")
            .contains("- An uncategorized change")
            .doesNotContain("1.2.3")
        println(actual)
    }

    @Test fun format_log_with_cleared_settings() {
        val settings = SemverSettings()
        settings.changeLogTexts.clear()
        val changeLog = createChangeLog()

        val actual = ChangeLogFormatter(settings, settings.changeLogTexts).formatLog(changeLog)

        assertThat(actual).isEmpty()
    }

    private fun createChangeLog(): List<Commit> {
        val changeLog = listOf(
            "fix(#1): Bugfix 1",
            "fix(#1): Bugfix 1",
            "fix(deps): Bugfix broken deps",
            "feat(#2): A feature",
            "fix(#5)!: A breaking change\nmore text",
            "build(deps): A build change",
            "release: 1.2.3-alpha",
            "test: Added some tests",
            "ci: A CI change",
            "xyz: Some other change",
            "An uncategorized change"
        )
        return changeLog.map { Commit(it,  "", emptySequence()) }
    }
}
