/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package git.semver.plugin.gradle

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

/**
 * A simple unit test for the 'git.semver.plugin.gradle.greeting' plugin.
 */
class GitSemverPluginExtensionTest {
    @Test
    fun `plugin extension`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.jmongard.git-semver-plugin")

        val semver = project.extensions.getByName("semver") as GitSemverPluginExtension

        assertThat(semver.infoVersion).isNotNull()
        assertThat(semver.changeLog).isNotNull()
        assertThat(semver.noDirtyCheck).isFalse()
        assertThat(semver.defaultPreRelease).isEqualTo("SNAPSHOT")
    }

    @Test
    fun `plugin extension with project properties`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.extensions.extraProperties.set("defaultPreRelease", "NEXT")
        project.extensions.extraProperties.set("noDirtyCheck", "true")
        project.plugins.apply("com.github.jmongard.git-semver-plugin")

        val semver = project.extensions.getByName("semver") as GitSemverPluginExtension

        assertThat(semver.noDirtyCheck).isTrue()
        assertThat(semver.defaultPreRelease).isEqualTo("NEXT")
    }
}
