/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package git.semver.plugin.gradle

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatCode
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.io.TempDir
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource
import java.nio.file.Path
import kotlin.test.Test

/**
 * A simple unit test for the 'git.semver.plugin.gradle.greeting' plugin.
 */
class GitSemverPluginTest {
    @TempDir
    lateinit var tempDir: Path

    @ParameterizedTest
    @ValueSource(strings = ["printVersion", "printSemVersion", "printInfoVersion", "printChangeLog"])
    fun `plugin register print tasks`(name: String) {
        val outFile = tempDir.resolve("print.txt")
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.jmongard.git-semver-plugin")
        val c = project.extensions.findByName("semver") as GitSemverPluginExtension
        c.defaultPreRelease = "XYZ"

        val task = project.tasks.findByName(name) as PrintTask

        assertThat(task).isNotNull()
        assertThatCode { task.print() }.doesNotThrowAnyException()
        task.setFile(outFile.toString())
        task.print();
        assertThat(outFile).exists().isNotEmptyFile().content().doesNotContain("SNAPSHOT")
    }

    @Test
    fun `plugin register release tasks`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.jmongard.git-semver-plugin")

        val task = project.tasks.findByName("releaseVersion") as ReleaseTask

        assertThat(task).isNotNull()
        assertThatCode {
            task.setNoCommit(true)
            task.setNoCommit(false)
            task.setNoTag(true)
            task.setNoTag(false)
            task.setPreRelease("alpha1")
            task.setMessage("A Message")
            task.setTag(true)
            task.setTag(false)
            task.setCommit(true)
            task.setCommit(false)
            task.setNoDirty(false)
            task.setNoDirty(true)
            task.createRelease()
        }.doesNotThrowAnyException()
    }
}
